spring:
    application:
      name: spring-cloud-task

    datasource:
      url: jdbc:mariadb://localhost:3306/task
      username: root
      password: password
      driver-class-name: org.mariadb.jdbc.Driver
